distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:38941'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:43503'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:42585'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:41441'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:36361'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:41767'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:38377'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:38697'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:35775'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:34011'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:41815'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:43155'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:42597'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:42859'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:43653'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:33717'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:41243'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:44539'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:36095'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:42587'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:43105'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:36001'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:46483'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:44583'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:42103'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:37043'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:45245'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:46681'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:45307'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:38933'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:39095'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:36947'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:39805'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:36805'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:40369'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:34907'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:45177'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:43611'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:38885'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:39825'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:34057'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:41891'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:44399'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:32831'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:43855'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:44091'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:42613'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:36301'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:37713'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:46095'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:45913'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:44507'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:39035'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:43429'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:44183'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:36987'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:40225'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:44577'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:40671'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:37733'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:38935'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:44849'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:36091'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:44045'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:41899'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:38523'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:39385'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:44169'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:40207'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:42417'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:42849'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:43261'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:38537'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:37395'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:46183'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:37915'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:43821'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:36013'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:38951'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:39675'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:36855'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:46247'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:35475'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:34859'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:44495'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:43483'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:37479'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:42521'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:35039'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:41217'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:35145'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:39863'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:42431'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:43803'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:44667'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:41799'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:34567'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:37431'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:38753'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.101.219:41311'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 2667 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 2687 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 2661 exited with status 1
distributed.nanny - INFO - Worker process 2678 exited with status 1
distributed.nanny - INFO - Worker process 2654 exited with status 1
distributed.nanny - INFO - Worker process 2664 exited with status 1
distributed.nanny - INFO - Worker process 2669 exited with status 1
distributed.nanny - INFO - Worker process 2675 exited with status 1
distributed.nanny - INFO - Worker process 2685 exited with status 1
distributed.nanny - INFO - Worker process 2691 exited with status 1
distributed.nanny - INFO - Worker process 2693 exited with status 1
distributed.nanny - INFO - Worker process 2656 exited with status 1
distributed.nanny - INFO - Worker process 2655 exited with status 1
distributed.nanny - INFO - Worker process 2672 exited with status 1
distributed.nanny - INFO - Worker process 2698 exited with status 1
distributed.nanny - INFO - Worker process 2681 exited with status 1
distributed.nanny - INFO - Worker process 2716 exited with status 1
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:41441'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:42585'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:38941'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:43503'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:41767'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:36361'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:38377'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:38697'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:35775'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:34011'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:41815'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:43155'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:42597'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:42859'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:43653'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:41243'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:36001'
distributed.nanny - INFO - Worker process 2725 exited with status 1
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:42103'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
distributed.nanny - INFO - Worker process 2729 exited with status 1
distributed.nanny - INFO - Worker process 2705 exited with status 1
distributed.nanny - INFO - Worker process 2699 exited with status 1
distributed.nanny - INFO - Worker process 2710 exited with status 1
distributed.nanny - INFO - Worker process 2713 exited with status 1
distributed.nanny - INFO - Worker process 2703 exited with status 1
distributed.nanny - INFO - Worker process 2721 exited with status 1
distributed.nanny - INFO - Worker process 2732 exited with status 1
distributed.nanny - INFO - Worker process 2718 exited with status 1
distributed.nanny - INFO - Worker process 2745 exited with status 1
distributed.nanny - INFO - Worker process 2736 exited with status 1
distributed.nanny - INFO - Worker process 2734 exited with status 1
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
distributed.nanny - INFO - Worker process 2785 exited with status 1
distributed.nanny - INFO - Worker process 2819 exited with status 1
distributed.nanny - INFO - Worker process 2782 exited with status 1
distributed.nanny - INFO - Worker process 2868 exited with status 1
distributed.nanny - INFO - Worker process 2922 exited with status 1
distributed.nanny - INFO - Worker process 2918 exited with status 1
distributed.nanny - INFO - Worker process 2898 exited with status 1
distributed.nanny - INFO - Worker process 2889 exited with status 1
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
distributed.nanny - INFO - Worker process 2815 exited with status 1
distributed.nanny - INFO - Worker process 2754 exited with status 1
distributed.nanny - INFO - Worker process 2758 exited with status 1
distributed.nanny - INFO - Worker process 2802 exited with status 1
distributed.nanny - INFO - Worker process 2926 exited with status 1
distributed.nanny - INFO - Worker process 2830 exited with status 1
distributed.nanny - INFO - Worker process 2764 exited with status 1
distributed.nanny - INFO - Worker process 2768 exited with status 1
distributed.nanny - INFO - Worker process 2821 exited with status 1
distributed.nanny - INFO - Worker process 2770 exited with status 1
distributed.nanny - INFO - Worker process 2946 exited with status 1
distributed.nanny - INFO - Worker process 2793 exited with status 1
distributed.nanny - INFO - Worker process 2780 exited with status 1
distributed.nanny - INFO - Worker process 2751 exited with status 1
distributed.nanny - INFO - Worker process 2858 exited with status 1
distributed.nanny - INFO - Worker process 2773 exited with status 1
distributed.nanny - INFO - Worker process 2797 exited with status 1
distributed.nanny - INFO - Worker process 2834 exited with status 1
distributed.nanny - INFO - Worker process 2812 exited with status 1
distributed.nanny - INFO - Worker process 2796 exited with status 1
distributed.nanny - INFO - Worker process 2908 exited with status 1
distributed.nanny - INFO - Worker process 2864 exited with status 1
distributed.nanny - INFO - Worker process 2790 exited with status 1
distributed.nanny - INFO - Worker process 2748 exited with status 1
distributed.nanny - INFO - Worker process 2885 exited with status 1
distributed.nanny - INFO - Worker process 2895 exited with status 1
distributed.nanny - INFO - Worker process 2904 exited with status 1
distributed.nanny - INFO - Worker process 2902 exited with status 1
distributed.nanny - INFO - Worker process 2951 exited with status 1
distributed.nanny - INFO - Worker process 2911 exited with status 1
distributed.nanny - INFO - Worker process 2929 exited with status 1
distributed.nanny - INFO - Worker process 2958 exited with status 1
distributed.nanny - INFO - Worker process 2949 exited with status 1
distributed.nanny - INFO - Worker process 2966 exited with status 1
distributed.nanny - INFO - Worker process 2960 exited with status 1
distributed.nanny - INFO - Worker process 2956 exited with status 1
distributed.nanny - INFO - Worker process 2824 exited with status 1
distributed.nanny - INFO - Worker process 2938 exited with status 1
distributed.nanny - INFO - Worker process 2962 exited with status 1
distributed.nanny - INFO - Worker process 2836 exited with status 1
distributed.nanny - INFO - Worker process 2964 exited with status 1
distributed.nanny - INFO - Worker process 2832 exited with status 1
distributed.nanny - INFO - Worker process 2852 exited with status 1
distributed.nanny - INFO - Worker process 2875 exited with status 1
distributed.nanny - INFO - Worker process 2944 exited with status 1
distributed.nanny - INFO - Worker process 2953 exited with status 1
distributed.nanny - INFO - Worker process 2900 exited with status 1
distributed.nanny - INFO - Worker process 2871 exited with status 1
distributed.nanny - INFO - Worker process 2878 exited with status 1
distributed.nanny - INFO - Worker process 2855 exited with status 1
distributed.nanny - INFO - Worker process 2860 exited with status 1
distributed.nanny - INFO - Worker process 2916 exited with status 1
distributed.nanny - INFO - Worker process 2936 exited with status 1
distributed.nanny - INFO - Worker process 2939 exited with status 1
distributed.nanny - INFO - Worker process 2879 exited with status 1
distributed.nanny - INFO - Worker process 2850 exited with status 1
distributed.nanny - INFO - Worker process 2968 exited with status 1
distributed.nanny - INFO - Worker process 2833 exited with status 1
distributed.nanny - INFO - Worker process 2816 exited with status 1
distributed.nanny - INFO - Worker process 2862 exited with status 1
distributed.nanny - INFO - Worker process 2913 exited with status 1
distributed.nanny - INFO - Worker process 2806 exited with status 1
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:33717'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:44539'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:36095'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:42587'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:43105'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:46483'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:44583'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:37043'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:45245'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:46681'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:45307'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:38933'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:37431'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:41311'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:39095'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:36947'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:39805'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:36805'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:34907'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:40369'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:45177'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:43611'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:39825'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:34057'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:38885'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:41891'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:44399'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:32831'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:43855'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:44091'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:42613'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:36301'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:37713'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:46095'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:45913'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:44507'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:39035'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:36987'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:44183'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:40225'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:44577'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:43429'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:38935'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:40671'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:44849'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:37733'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:41899'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:36091'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:44045'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:38523'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:39385'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:44169'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:40207'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:42417'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:42849'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:43261'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:46183'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:37395'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:38537'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:37915'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:43821'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:38951'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:39675'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:36855'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:46247'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:36013'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:35475'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:34859'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:44495'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:42521'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:37479'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:43483'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:35039'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:41217'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:35145'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:39863'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:42431'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:43803'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:44667'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:41799'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:34567'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.101.219:38753'
distributed.dask_worker - INFO - End worker
