distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:38745'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:34523'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:41089'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:38349'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:33911'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:34063'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:45059'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:44653'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:41617'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:43447'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:41889'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:39625'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:42743'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:36087'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:33683'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:44057'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:42873'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:37601'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:33141'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:37227'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:38035'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:39027'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:35807'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:46531'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:43711'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:32991'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:40949'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:42297'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:34541'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:39467'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:42795'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:41705'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:46959'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:45833'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:38163'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:43845'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:44927'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:38923'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:43681'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:41651'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:37283'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:42561'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:42183'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:44995'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:41687'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:37745'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:39125'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:38691'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:44071'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:37895'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:46321'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:43001'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:35885'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:45353'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:34247'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:45003'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:36269'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:33083'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:46491'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:38877'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:34183'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:40877'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:36401'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:46375'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:36823'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:34287'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:40137'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:36673'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:36883'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:45841'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:34169'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:36419'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:36543'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:33443'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:35423'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:35731'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:36009'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:46035'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:32819'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:41245'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:36119'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:43361'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:34741'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:34065'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:40153'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:36647'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:40825'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:46945'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:33371'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:35107'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:33833'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:44775'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:36121'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:42255'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:35013'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:39973'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:33143'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:37217'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:35453'
distributed.nanny - INFO -         Start Nanny at: 'tcp://198.202.102.46:44583'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 103664 exited with status 1
distributed.nanny - INFO - Worker process 103655 exited with status 1
distributed.nanny - INFO - Worker process 103661 exited with status 1
distributed.nanny - INFO - Worker process 103667 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 103639 exited with status 1
distributed.nanny - INFO - Worker process 103641 exited with status 1
distributed.nanny - INFO - Worker process 103649 exited with status 1
distributed.nanny - INFO - Worker process 103670 exited with status 1
distributed.nanny - INFO - Worker process 103646 exited with status 1
distributed.nanny - INFO - Worker process 103637 exited with status 1
distributed.nanny - INFO - Worker process 103652 exited with status 1
distributed.nanny - INFO - Worker process 103704 exited with status 1
distributed.nanny - INFO - Worker process 103672 exited with status 1
distributed.nanny - INFO - Worker process 103730 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 103678 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 103658 exited with status 1
distributed.nanny - INFO - Worker process 103691 exited with status 1
distributed.nanny - INFO - Worker process 103636 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 103700 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 103697 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 103687 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 103713 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 103685 exited with status 1
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:43447'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:41889'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:39625'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:42743'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:36087'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:44057'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:37227'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:46531'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:42795'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:38745'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:41089'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:38349'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:34523'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:33911'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:45059'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:34063'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:44653'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:41617'
distributed.nanny - INFO - Worker process 103682 exited with status 1
distributed.nanny - INFO - Worker process 103708 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 103732 exited with status 1
distributed.nanny - INFO - Worker process 103721 exited with status 1
distributed.nanny - INFO - Worker process 103676 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 103723 exited with status 1
distributed.nanny - INFO - Worker process 103710 exited with status 1
distributed.nanny - INFO - Worker process 103695 exited with status 1
distributed.nanny - INFO - Worker process 103735 exited with status 1
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/process.py", line 192, in _run
    target(*args, **kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 728, in _run
    worker = Worker(**worker_kwargs)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/worker.py", line 537, in __init__
    os.makedirs(local_directory, exist_ok=True)
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/scratch/ntolley/job_1227860'
distributed.nanny - INFO - Worker process 103835 exited with status 1
distributed.nanny - INFO - Worker process 103853 exited with status 1
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:33683'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:42873'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:37601'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:33141'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:38035'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:39027'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:35807'
distributed.nanny - INFO - Worker process 103778 exited with status 1
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:43711'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:40949'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:32991'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:42297'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:34541'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:39467'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:41705'
distributed.nanny - INFO - Worker process 103796 exited with status 1
distributed.nanny - INFO - Worker process 103818 exited with status 1
distributed.nanny - INFO - Worker process 103762 exited with status 1
distributed.nanny - INFO - Worker process 103886 exited with status 1
distributed.nanny - INFO - Worker process 103909 exited with status 1
distributed.nanny - INFO - Worker process 103929 exited with status 1
distributed.nanny - INFO - Worker process 103940 exited with status 1
distributed.nanny - INFO - Worker process 103746 exited with status 1
distributed.nanny - INFO - Worker process 103772 exited with status 1
distributed.nanny - INFO - Worker process 103743 exited with status 1
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
distributed.nanny - INFO - Worker process 103820 exited with status 1
distributed.nanny - INFO - Worker process 103892 exited with status 1
distributed.nanny - INFO - Worker process 103903 exited with status 1
distributed.nanny - INFO - Worker process 103837 exited with status 1
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:46959'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:38163'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:41651'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:42183'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:44995'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:37895'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:33083'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:40877'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:40137'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:35423'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:40153'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:33833'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:42255'
distributed.nanny - INFO - Worker process 103784 exited with status 1
distributed.nanny - INFO - Worker process 103872 exited with status 1
distributed.nanny - INFO - Worker process 103755 exited with status 1
distributed.nanny - INFO - Worker process 103791 exited with status 1
distributed.nanny - INFO - Worker process 103748 exited with status 1
distributed.nanny - INFO - Worker process 103793 exited with status 1
distributed.nanny - INFO - Worker process 103817 exited with status 1
distributed.nanny - INFO - Worker process 103918 exited with status 1
distributed.nanny - INFO - Worker process 103896 exited with status 1
distributed.nanny - INFO - Worker process 103849 exited with status 1
distributed.nanny - INFO - Worker process 103857 exited with status 1
distributed.nanny - INFO - Worker process 103935 exited with status 1
distributed.nanny - INFO - Worker process 103840 exited with status 1
distributed.nanny - INFO - Worker process 103806 exited with status 1
distributed.nanny - INFO - Worker process 103865 exited with status 1
distributed.nanny - INFO - Worker process 103868 exited with status 1
distributed.nanny - INFO - Worker process 103874 exited with status 1
distributed.nanny - INFO - Worker process 103877 exited with status 1
distributed.nanny - INFO - Worker process 103863 exited with status 1
distributed.nanny - INFO - Worker process 103880 exited with status 1
distributed.nanny - INFO - Worker process 103888 exited with status 1
distributed.nanny - INFO - Worker process 103946 exited with status 1
distributed.nanny - INFO - Worker process 103938 exited with status 1
distributed.nanny - INFO - Worker process 103950 exited with status 1
distributed.nanny - INFO - Worker process 103942 exited with status 1
distributed.nanny - INFO - Worker process 103802 exited with status 1
distributed.nanny - INFO - Worker process 103859 exited with status 1
distributed.nanny - INFO - Worker process 103760 exited with status 1
distributed.nanny - INFO - Worker process 103780 exited with status 1
distributed.nanny - INFO - Worker process 103809 exited with status 1
distributed.nanny - INFO - Worker process 103753 exited with status 1
distributed.nanny - INFO - Worker process 103776 exited with status 1
distributed.nanny - INFO - Worker process 103943 exited with status 1
distributed.nanny - INFO - Worker process 103769 exited with status 1
distributed.nanny - INFO - Worker process 103811 exited with status 1
distributed.nanny - INFO - Worker process 103739 exited with status 1
distributed.nanny - INFO - Worker process 103804 exited with status 1
distributed.nanny - INFO - Worker process 103833 exited with status 1
distributed.nanny - INFO - Worker process 103788 exited with status 1
distributed.nanny - INFO - Worker process 103931 exited with status 1
distributed.nanny - INFO - Worker process 103915 exited with status 1
distributed.nanny - INFO - Worker process 103900 exited with status 1
distributed.nanny - INFO - Worker process 103924 exited with status 1
distributed.nanny - INFO - Worker process 103845 exited with status 1
distributed.nanny - INFO - Worker process 103828 exited with status 1
distributed.nanny - INFO - Worker process 103883 exited with status 1
distributed.nanny - INFO - Worker process 103913 exited with status 1
distributed.nanny - INFO - Worker process 103907 exited with status 1
distributed.nanny - INFO - Worker process 103948 exited with status 1
distributed.nanny - INFO - Worker process 103933 exited with status 1
distributed.nanny - INFO - Worker process 103922 exited with status 1
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/home/ntolley/anaconda3/envs/sbi/lib/python3.8/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:39973'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:33143'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:45833'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:43845'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:44927'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:38923'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:43681'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:37283'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:42561'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:41687'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:37745'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:39125'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:38691'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:44071'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:46321'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:43001'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:45353'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:35885'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:34247'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:36269'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:45003'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:46491'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:34183'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:36401'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:38877'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:46375'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:34287'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:36823'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:36673'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:45841'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:36419'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:36883'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:36543'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:34169'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:35731'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:33443'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:46035'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:36009'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:32819'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:41245'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:36119'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:43361'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:34741'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:34065'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:36647'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:46945'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:40825'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:33371'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:37217'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:35107'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:44583'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:44775'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:35453'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:36121'
distributed.nanny - INFO - Closing Nanny at 'tcp://198.202.102.46:35013'
distributed.dask_worker - INFO - End worker
